import './globals.css'
import "../theme/main.scss";
import Layout from '@/components/Layout';

export const metadata = {
  title: 'App server',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <Layout>{children}</Layout>
  )
}
