import './globals.css'
import "../theme/main.scss";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../assets/fonts/bodas-2023/styles.css";

import RootLayout from '@/components/Layout';

export const metadata = {
  title: 'App server',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  
  return (
    <RootLayout>{children}</RootLayout>
  )
}
